### ISSUE TITLE
No link to article explaining why there is so much slash in fanfiction.

### ISSUE THREAD

**Issue by void-elf** [colah/Fanfiction-Graphs-Post#2]
I am referring to this string: "(For an exploration of why there is so much slash fanficiton, see this article.)" << you forgot to link the article

**Comment by colah** [comment]
Thanks for catching that! I can't find the link to the article, so I'm just deleting that line.

**Comment by colah** [comment]
Thanks for catching that! I can't find the link to the article, so I'm just deleting that line.
